version: '3.8'

services:

  solr-ut:
    image: solr:8
    volumes:
      - ./test/solr/configsets:/configsets:ro
    ports:
      - "8983:8983"
    command: >
      bash -c "precreate-core term_search_core1 /configsets/term_search
      && precreate-core prop_search_core1 /configsets/property_search
      && solr-foreground"

  redis-ut:
    image: redis
    ports:
      - "6379:6379"

  mgrep-ut:
    image: ontoportal/mgrep-ncbo:0.1
    ports:
      - "55556:55555"


  4store-ut:
    image: bde2020/4store
    platform: linux/amd64
    ports:
      - "9000:9000"
    command: >
      bash -c "4s-backend-setup --segments 4 ontoportal_kb
      && 4s-backend ontoportal_kb
      && 4s-httpd -D -s-1 -p 9000 ontoportal_kb"

volumes:
  bundle:
